"""Internationalization labels for report generation."""

LABELS = {
    "en": {
        # Cover / header
        "report_title_default": "Information Feed Digest",
        "date": "Date",
        "sources": "Sources",
        "total": "Total",
        "items": "items",
        "keywords_label": "Keywords",
        "time_range": "Time Range",
        "profile": "Profile",

        # Section headers
        "executive_summary": "Executive Summary",
        "academic_papers": "Academic Papers",
        "news_insights": "News & Insights",
        "source_health": "Source Health",

        # Item fields -- academic
        "authors": "Authors",
        "pub_date": "Date",
        "source": "Source",
        "venue": "Venue",
        "citations": "Citations",
        "tldr": "TL;DR",
        "relevance": "Relevance",
        "matched_keywords": "Keywords",

        # Item fields -- social/news
        "account": "Account",
        "likes": "Likes",
        "comments": "Comments",
        "shares": "Shares",

        # Footer
        "generated_by": "Generated by info-feed-aggregator at",
    },
    "zh": {
        "report_title_default": "信息聚合速报",
        "date": "日期",
        "sources": "数据来源",
        "total": "总计",
        "items": "条",
        "keywords_label": "关键词",
        "time_range": "时间范围",
        "profile": "搜索方案",

        "executive_summary": "综述摘要",
        "academic_papers": "学术论文",
        "news_insights": "资讯动态",
        "source_health": "数据源状态",

        "authors": "作者",
        "pub_date": "发布日期",
        "source": "来源",
        "venue": "期刊/会议",
        "citations": "被引次数",
        "tldr": "一句话总结",
        "relevance": "相关度",
        "matched_keywords": "匹配关键词",

        "account": "账号",
        "likes": "点赞",
        "comments": "评论",
        "shares": "分享",

        "generated_by": "由 info-feed-aggregator 生成于",
    },
}


def get_labels(language: str = "en") -> dict:
    """Return label dict for the given language, falling back to English."""
    return LABELS.get(language, LABELS["en"])
